name: Build

on:
  push:
    branches:
      - '*'
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        path: ./server
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: jpd002/playservices
        tag_with_ref: true
    - name: Update Test Environment
      uses: einaregilsson/beanstalk-deploy@v14
      if: github.ref == 'refs/heads/develop'
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: PlayServices
        environment_name: playservices-test
        version_label: playservices-docker-develop
        region: us-west-2
